image: cirrusci/flutter:stable

stages:
  - build
  - analyze
  - test

before_script:
  - flutter pub get
  - flutter clean

build:
  stage: build

  script:
    - flutter build aot

  tags:
    - shared

  only:
    - merge_requests

uinttests:
  stage: test
  script:
    - flutter test test/*
  tags:
    - shared
  only:
    - merge_requests
